name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install ansible
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3 
      - name: Run Ansible playbook to install Docker and Docker Compose
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/main.yml
          inventory: ansible/inventory.ini
          extra-vars: |
            ansible_python_interpreter=/usr/bin/python3
          become: true
          become-user: root
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: saurav-django-app:latest

      - name: SSH into EC2 instance
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-231-165-225.ap-northeast-1.compute.amazonaws.com "cd /django && docker-compose pull && docker-compose up -d"
